monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/dev_app.log'
            level: debug
            channels: ['!event', '!doctrine']

        doctrine:
            type: stream
            path: '%kernel.logs_dir%/dev_doctrine.log'
            level: debug
            channels: ['doctrine']

        stdout:
            type: stream
            path: '%kernel.logs_dir%/dev_stdout.log'
            level: info
            channels: ['console']

        stderr:
            type: stream
            path: '%kernel.logs_dir%/dev_stderr.log'
            level: error
            channels: ['console']

        event:
            type: stream
            path: '%kernel.logs_dir%/dev_event.log'
            level: info
            channels: ['event']

        security:
            type: stream
            path: '%kernel.logs_dir%/dev_security.log'
            level: info
            channels: ['security']
